spring:
  application:
    name: leadfy-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/leadfy}
    username: ${DB_USERNAME:leadfy}
    password: ${DB_PASSWORD:leadfy}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
